### ISSUE TITLE
Create lifecycle rule that expires objects after N days on S3 bucket

### ISSUE THREAD

**Issue by alex** [nelhage/llama#1]
S3 supports a feature where objects older than N days are automatically deleted. I think the S3 bucket use for llama should have one of these. I just enabled one manually for my bucket, and used 28 days as the time period.

**Comment by nelhage** [comment]
I've done the same, and have a mention in the README (which is really getting out of control :)): https://github.com/nelhage/llama/#cleaning-up-old-objects

I'll add it to my TODO list for `llama bootstrap`

**Comment by nelhage** [comment]
This is done in the new `llama bootstrap`.
