### ISSUE TITLE
Use `-fdebug-prefix-map=old=new` when compiling with gcc/clang

### ISSUE THREAD

**Issue by nvartolomei** [nelhage/llama#54]
Currently, symbols point to temporary folders as created on lambda `0. /tmp/llama.565826462/_root/home/nv/[...]` this makes stacktraces quite ugly.

Think this can be fixed with passing `-fdebug-prefix-map`.

https://gcc.gnu.org/onlinedocs/gcc/Debugging-Options.html

```
-fdebug-prefix-map=old=new
When compiling files residing in directory old, record debugging information describing them as if the files resided in directory new instead. This can be used to replace a build-time path with an install-time path in the debug info. It can also be used to change an absolute path to a relative path by using . for new. This can give more reproducible builds, which are location independent, but may require an extra command to tell GDB where to find the source files. 
```

**Comment by nelhage** [comment]
Great suggestion! Can you test whether https://github.com/nelhage/llama/pull/55 helps for you? There's a bit of complexity as mentioned in the issue, but it should get most of the way there.
